/* COMMIT E ROLLBACK */

/* DELETANTO O REGISTRO COM A CLAUSULA DELETE */
DELETE FROM CLIENTE; -- VAI DELETAR A TABELA TODA


SELECT COUNT(*) FROM CLIENTE; --  SELECIONAR TABELA  CLIENTE E CONTA 

DELETE FROM CLIENTE  -- DELETA DA TABELA CLEINTE 
WHERE NOME = 'ANA';   --TODOS CLIENTES COM O NOME ANA

SELECT COUNT  (*) FROM CLIENTE; -- APRESENTA A QUANTIDADE NOVA 

/*A CLÁUSULA DELETE */





-- ANTES DE DELETAR UM REGISTRO CONSULTAR ANTEs EXEMPLO

SELECT * FROM CLIENTE
WHERE NOME = 'cassio luciano da silva '
AND EMAIL = 'cassiolucianodasilva@gmail';


-- DELETANDO TODOS REGISTOS 
DELETE FROM CLIENTE
WHERE NOME = 'cassio luciano da silva '
AND EMAIL = 'cassiolucianodasilva@gmail';


INSERT INTO CLIENTE VALUES('cassio ','m','c.caa@gmail.com',89856565,'5252-5252','rua coper leaf -  williamnsburgs - kitcher');