
/*ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS */

CLIENTE 

NOME - CARACTER (30)
CPF - NUMERICO (11)
EMAIL  - CARACTER( 30 )
TELEFONE - CARACTER ( 30 )
ENDERECO - CARACTER ( 100 )
SEXO - CARACTER ( 1 )

/* PROCESSOS DE MODELAGEM */

/* FASE 01 E FASE 02 - AD ADM DE DADOS */

MODELAGEM CONCEITUAL - RASCUNHO 
MODELAGEM LOGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA / AD */
MODELAGEM FIDICA - SCRIPTS DE BANCO

CRIANDO O BANCO E AS TABELAS
-----------------------------------------------

/* INICIANDO A MODELAGEM FÍSICA */

/* CRIANDO O BANCO DE DADOS */

CREATE DATABASE EXEMPPLO    /*OBS QUE O EXEMPLO NÃO FINALIZA COM ; E O SQL FICA ESPERANDO FINALIZAR A LINHA*/    

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO, */

USE PROJETO;


/* CRIANDO A TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR (30),
	SEXO CHAR (1),
	EMAIL VARCHAR (30),
	CPF INT (11),
	TELEFONE VARCHAR (30),
	ENDERECO VARCHAR (100)	
);



/* MOSTRANDO AS TABELAS DO BANCO DE DADOS */

SHOW TABLES;


/* DESCOBRINDO A ESTRUTURA DA TABELA */


DESC CLIENTE;
