/*ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS */

TABELA - LIVROS 

/* ATRÍBUTOS */

NOME_LIVRO - CARACTER (100)
NOME_AUTOR - CARACTER (30)
SEXO - CARACTER ( 1 )
NUMERO_PAGINAS - NUMERICO (11)
NOME_EDITORA - CARACTER (100)
VALOR_LIVRO - NUMERICO (10)
ESTADO_EDITORA (UF) - CARACTER(2)
ANO_PUBLICACAO - NUMERICO (4)


/*CRIANDO BANCO DE DADOS */

CREATE DATABASE EXERCICIOS;

/*COMANDO PRA ACESSAR O BANCO */

USE EXERCICIOS;

/*CRIAR TABELA COM OS ATRIBUTOS */

CREATE TABLE LIVROS(
	NOME_LIVRO VARCHAR (30),
	NOME_AUTOR VARCHAR (30),
	SEXO CHAR (1),
	NUMERO_PAGINAS INT (11),
	NOME_EDITORA VARCHAR (30),
	VALOR_LIVRO float(10),
	UF VARCHAR(2),
	ANO_PUBLICACAO INT(4)
);


/* MOSTRANDO AS TABELAS DO BANCO DE DADOS */

SHOW TABLES;


/* DESCOBRINDO A ESTRUTURA DA TABELA */

DESC LIVROS;


/* INCLUIDO DADOS DO LIVRO */



/*VER TABELA COMPLETA NÃO USAR ESSE METODO, APENAS USANDO PORQUE O BANCO É PEQUENO*/

SELECT * FROM LIVROS;


INSERT INTO LIVROS VALUES ('O Morro Dos Ventos Uivantes', ' Brontë','M',368,'Principis
',24.90,'SP',2019),
('O Fim Em Doses Homeopáticas', 'Pires, Igor','M',450,'Principis
',39.90,'SP',2020),
('O Fim Em Doses Homeopáticas', 'Pires, Igor','M',450,'Principis
',39.90,'SP',2020),
('Longa Pétala De Mar', 'Allende, Isabel','F',280,'CASSIO
',49.90,'SP',2019),
('Pensando em tomar uma', 'cassio luciano da silva','m',600,'CASSIO
',100,'SP',1988),
('O Morro ', ' BRUTO','F',10,'ZÉ
',90.90,'RJ',2019),
('Eu ', ' 13 vidas','M',10,'FABRICA
',90.90,'RJ',2000);


/* 01 )TRAZER TODOS OS LIVROS */

SELECT NOME_LIVRO FROM LIVROS;

/* 02 )FILTRAR NOME DO LIVRO E DA EDITORA */

SELECT NOME_LIVRO, NOME_EDITORA FROM LIVROS;


/* 03 )FILTRAR NOME DO LIVRO E UM DO SEXO MASCULINO*/
SELECT NOME_LIVRO, UF, SEXO FROM LIVROS
WHERE SEXO = 'M';


/* 04 )FILTRAR NOME DO LIVRO O NUMERO DE PAGINAS DO SEXO FEMININO*/
SELECT NOME_LIVRO, NUMERO_PAGINAS, SEXO FROM LIVROS
WHERE SEXO = 'F';

/* 05 )APRESENTAR O VALOR DOS LIVROS DE SP*/
SELECT VALOR_LIVRO, UF FROM LIVROS
WHERE UF = 'SP';



/* 06 ) TRAZER OS DADOS DOS AUTORE DOS LIVROS PUBLICADOS EM SP E RJ COM OS ATORES DO SEXO MASCULINO*/
SELECT  NOME_AUTOR, NOME_LIVRO, SEXO, UF FROM LIVROS
WHERE SEXO = 'M' AND (UF = 'SP' OR UF = 'RJ') ;


