/* ULTILIZANDO O UPDATE PARA ATUALIZAR VALORES */


-- VISUALIZAR TABELA 
SELECT NOME, EMAIL
FROM CLIENTE;

--VAI ATUALIZAR TODA TABELA DA COLUNA EMAIL 
UPDATE CLIENTE 
SET EMAIL = 'cassiolucianodasilva@gmail.com';


/* WHERE - PARA SEMPRE  S2  */


-- 1  SELECIONE O CLIENTE 

SELECT * FROM CLIENTE
WHERE NOME = 'cassio luciano da silva';


-- 2   ATUALIZAR EMAIL  ( ATUALIZANDO DADOS DA TABELA USANDO O UPDATE )

UPDATE CLIENTE
SET EMAIL = 'cassiolucianodasilva@gmail'
WHERE NOME = 'cassio luciano da silva';






